#!/bin/bash

file="deploy.yaml"

add_file() {
    echo "---" >> $file
    echo "# Source:" $1 >> $file
    cat $1 >> $file
    echo "" >> $file
}

rm -f $file
echo "# Generated by KubeChat/build-deploy.sh" >> $file
add_file "kubechat/templates/server.fleet.yaml"
add_file "kubechat/templates/client.serverside.deployment.yaml"
add_file "kubechat/templates/client.serverside.service.yaml"
add_file "kubechat/templates/client.webassembly.deployment.yaml"
add_file "kubechat/templates/client.webassembly.service.yaml"
add_file "kubechat/templates/agones.deployment.yaml"
add_file "kubechat/templates/agones.service.yaml"
add_file "kubechat/templates/gateway.deployment.yaml"
add_file "kubechat/templates/gateway.service.yaml"
add_file "kubechat/templates/ingress.yaml"

echo "Generated" $file
