version: '3.4'

services:
  client.kubechat.com:
    image: ${DOCKER_REGISTRY-}kubechatclient
    build:
      context: .
      dockerfile: KubeChat.Client/Dockerfile.compose

  server.kubechat.com:
    image: ${DOCKER_REGISTRY-}kubechatserver
    build:
      context: .
      dockerfile: KubeChat.Server/Dockerfile.compose

