version: '3.4'

services:
  serverside.client.kubechat.com:
    image: ${DOCKER_REGISTRY-}kubechatclientserverside
    build:
      context: .
      dockerfile: KubeChat.Client.ServerSide/Dockerfile.compose

  server.kubechat.com:
    image: ${DOCKER_REGISTRY-}kubechatserver
    build:
      context: .
      dockerfile: KubeChat.Server/Dockerfile.compose

