version: '3.4'

services:
  kubechat.client:
    image: ${DOCKER_REGISTRY-}kubechatclient
    build:
      context: .
      dockerfile: KubeChat.Client/Dockerfile.compose

  kubechat.server:
    image: ${DOCKER_REGISTRY-}kubechatserver
    build:
      context: .
      dockerfile: KubeChat.Server/Dockerfile.compose

