version: '3.4'

services:
  client-serverside-service:
    image: ${DOCKER_REGISTRY-}kubechat-client-serverside
    build:
      context: .
      dockerfile: KubeChat.Client.ServerSide/Dockerfile

  server-service:
    image: ${DOCKER_REGISTRY-}kubechat-server
    build:
      context: .
      dockerfile: KubeChat.Server/Dockerfile

