apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: kubechat
  labels:
    app: agones
    chart: agones-1.11.0
    release: agones-manual
    heritage: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk-access
  namespace: kubechat
  labels:
    app: agones
    chart: agones-1.11.0
    release: agones-manual
    heritage: Helm
subjects:
- kind: User
  name: system:serviceaccount:kubechat:agones-sdk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
