apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: kubechat
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: xxatrain223/kubechatclient:0.1.1
        ports:
        - containerPort: 80