apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: kubechat
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: xxatrain223/kubechat-server:0.1.4
        ports:
        - containerPort: 80
        env:
        - name: KubernetesResource
          value: Pod
